### ISSUE TITLE
Location of the borg directory

### ISSUE THREAD

**Issue by eflanigan00** [emacscollective/borg#31] opened 2017-12-17 22:27 UTC
I have not used the package yet but it looks very promising.
Is it possible to configure this to work in a folder:
.emacs.d/borg/ instead of .emacs.d
 
I have at least 50 packages and having them in the .emacs.d directory isn't something I want to manage.

**Comment by tarsius** [comment] 2017-12-17 22:32
I plan to make it easier to use `borg` alongside `package.el`. For an early draft see https://github.com/emacscollective/borg/pull/27. And additionally I started working on `borg` again just today. I have concentrated on other issue so far but maybe I will get to this tomorrow.

**Comment by eflanigan00** [comment] 2017-12-17 22:35
Thanks for the great work! No rush.

**Comment by tarsius** [comment] 2017-12-17 22:42
> Is it possible to configure this to work in a folder: .emacs.d/borg/ instead of .emacs.d

That is possible, but doesn't have the effect you are probably after. `~/.emacs.d/borg/` then "becomes" `~/.emacs.d/` and you have to start Emacs using `emacs -Q --load ~/.emacs.d/borg/`. This feature is more intended to be used like `emacs -Q --load /tmp/lets-try-borg`.

But you can use `borg` and `package` alongside in `~/.emacs.d`. `borg` installs packages in `lib/` and `package.el` in `elpa/`. `borg` doesn't take control over other files in the repository so you can just make `~/.emacs.d` the top-level of the repository as expected by `borg` without messing with `package.el` packages and other things. You probably want to add some entries to `.gitignore` though, beginning with `/elpa/`.

**Comment by tarsius** [comment] 2017-12-17 22:43
Closing as a duplicate of #12, but feel free commenting here.

**Closed by tarsius** 2017-12-17 22:43 UTC

**Comment by eflanigan00** [comment] 2018-04-16 03:54
If you can make borg work in a directory I would love to try it.
At this point I'm not willing to place 50+ repos in my .emacs.d/ directory.
I would be willing to place them in a .emacs.d/borg/ directory
